from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class JobProgress(BaseModel):
    progress: int = Field(default=0, ge=0, le=100)
    message: str = "Queued"


class DecodeResultContract(BaseModel):
    style_label: str = "Other"
    style_confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    svg_url: str = ""
    layers: List[Dict[str, Any]] = Field(default_factory=list)
    colors: List[Dict[str, Any]] = Field(default_factory=list)
    motifs: List[Dict[str, Any]] = Field(default_factory=list)
    weave_matrix: Optional[str] = None
    float_check_passed: bool = True
    analysis_card: str = "Generated by SJDAS"
    weave_recommendation: str = "Review and export"
    alert: Optional[str] = None


def normalize_decode_result(payload: Dict[str, Any]) -> DecodeResultContract:
    """
    Convert mixed legacy decode payloads into one stable shape.
    """
    return DecodeResultContract(
        style_label=payload.get("style_label") or payload.get("styleLabel") or "Other",
        style_confidence=payload.get("style_confidence") or payload.get("styleConfidence") or 0.0,
        svg_url=payload.get("svg_url") or payload.get("svgUrl") or "",
        layers=payload.get("layers") or [],
        colors=payload.get("colors") or [],
        motifs=payload.get("motifs") or [],
        weave_matrix=payload.get("weave_matrix") or payload.get("weaveMatrix"),
        float_check_passed=payload.get("float_check_passed")
        if payload.get("float_check_passed") is not None
        else payload.get("floatCheckPassed", True),
        analysis_card=payload.get("analysis_card") or payload.get("analysisCard") or "Generated by SJDAS",
        weave_recommendation=payload.get("weave_recommendation")
        or payload.get("weaveRecommendation")
        or "Review and export",
        alert=payload.get("alert"),
    )
