import type { DecodeResult, SareeStyle } from '@/src/store/useStudioStore';

type UnknownRecord = Record<string, unknown>;

function asNumber(value: unknown, fallback = 0): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

function asBoolean(value: unknown, fallback = true): boolean {
  return typeof value === 'boolean' ? value : fallback;
}

export function normalizeDecodeResult(payload: unknown): DecodeResult {
  const source = (payload || {}) as UnknownRecord;
  return {
    styleLabel: (source.styleLabel as SareeStyle) || (source.style_label as SareeStyle) || 'Other',
    styleConfidence: asNumber(source.styleConfidence ?? source.style_confidence, 0),
    svgUrl: asString(source.svgUrl ?? source.svg_url, ''),
    layers: Array.isArray(source.layers) ? (source.layers as DecodeResult['layers']) : [],
    colors: Array.isArray(source.colors) ? (source.colors as DecodeResult['colors']) : [],
    motifs: Array.isArray(source.motifs) ? (source.motifs as DecodeResult['motifs']) : [],
    weaveMatrix: asString(source.weaveMatrix ?? source.weave_matrix, ''),
    floatCheckPassed: asBoolean(source.floatCheckPassed ?? source.float_check_passed, true),
    analysisCard: asString(source.analysisCard ?? source.analysis_card, 'Generated by SJDAS'),
    weaveRecommendation: asString(
      source.weaveRecommendation ?? source.weave_recommendation,
      'Review and export',
    ),
    alert: asString(source.alert, ''),
  };
}
