from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class DecodeResultContract:
    style_label: str = "Other"
    style_confidence: float = 0.0
    svg_url: str = ""
    layers: List[Dict[str, Any]] = field(default_factory=list)
    colors: List[Dict[str, Any]] = field(default_factory=list)
    motifs: List[Dict[str, Any]] = field(default_factory=list)
    weave_matrix: Optional[str] = None
    float_check_passed: bool = True
    analysis_card: str = "Generated by SJDAS"
    weave_recommendation: str = "Review and export"
    alert: Optional[str] = None
