"""
Version Archival System for SJ-DAS
Automatically archives old versions with proper naming before updates
"""
import os
import shutil
from datetime import datetime
from pathlib import Path


class VersionArchiver:
    """Manages versioning and archival of project files."""

    def __init__(self, project_root: str = "."):
        self.project_root = Path(project_root)
        self.archive_dir = self.project_root / "archive"
        self.archive_dir.mkdir(exist_ok=True)

    def get_timestamp(self) -> str:
        """Get current timestamp for versioning."""
        return datetime.now().strftime("%Y%m%d_%H%M%S")

    def archive_file(self, file_path: str, description: str = "") -> str:
        """
        Archive a file with timestamp and description.

        Args:
            file_path: Path to file to archive
            description: Optional description of changes

        Returns:
            Path to archived file
        """
        file_path = Path(file_path)

        if not file_path.exists():
            print(f"Warning: {file_path} does not exist")
            return None

        # Create archive subdirectory based on file location
        relative_path = file_path.relative_to(
            self.project_root) if file_path.is_relative_to(
            self.project_root) else file_path
        archive_subdir = self.archive_dir / relative_path.parent
        archive_subdir.mkdir(parents=True, exist_ok=True)

        # Create archived filename
        timestamp = self.get_timestamp()
        stem = file_path.stem
        suffix = file_path.suffix

        if description:
            archive_name = f"{stem}_{timestamp}_{description}{suffix}"
        else:
            archive_name = f"{stem}_{timestamp}_backup{suffix}"

        archive_path = archive_subdir / archive_name

        # Copy file to archive
        shutil.copy2(file_path, archive_path)
        print(f"✅ Archived: {file_path} -> {archive_path}")

        return str(archive_path)

    def archive_directory(self, dir_path: str, description: str = "") -> str:
        """
        Archive an entire directory.

        Args:
            dir_path: Path to directory to archive
            description: Optional description

        Returns:
            Path to archived directory
        """
        dir_path = Path(dir_path)

        if not dir_path.exists():
            print(f"Warning: {dir_path} does not exist")
            return None

        timestamp = self.get_timestamp()

        if description:
            archive_name = f"{dir_path.name}_{timestamp}_{description}"
        else:
            archive_name = f"{dir_path.name}_{timestamp}_backup"

        archive_path = self.archive_dir / archive_name

        # Copy directory to archive
        shutil.copytree(dir_path, archive_path)
        print(f"✅ Archived directory: {dir_path} -> {archive_path}")

        return str(archive_path)

    def create_version_log(self, changes: list):
        """
        Create a version log file documenting changes.

        Args:
            changes: List of change descriptions
        """
        timestamp = self.get_timestamp()
        log_file = self.archive_dir / f"VERSION_LOG_{timestamp}.md"

        with open(log_file, 'w', encoding='utf-8') as f:
            f.write(f"# Version Log - {timestamp}\n\n")
            f.write(
                f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
            f.write("## Changes Made:\n\n")

            for i, change in enumerate(changes, 1):
                f.write(f"{i}. {change}\n")

            f.write("\n---\n")
            f.write("*Auto-generated by SJ-DAS Version Archival System*\n")

        print(f"✅ Version log created: {log_file}")
        return str(log_file)


def archive_current_version():
    """Archive current version before major updates."""
    archiver = VersionArchiver()

    print("=" * 60)
    print("SJ-DAS Version Archival System")
    print("=" * 60)

    # Files to archive
    critical_files = [
        "sj_das/ui/modern_designer_view.py",
        "sj_das/core/loom_engine.py",
        "sj_das/core/quantizer.py",
        "sj_das/core/design_recovery.py",
        "sj_das/ui/components/menu_builder.py",
        "requirements.txt"
    ]

    changes = [
        "Added 22 missing UI methods to PremiumDesignerView",
        "Refactored LoomEngine with enhanced error handling",
        "Refactored ColorQuantizerEngine with structured logging",
        "Refactored DesignRecoveryEngine with recover_design method",
        "Added build_tools_menu and build_help_menu to StandardMenuBuilder",
        "Updated requirements.txt with all dependencies",
        "Created enhanced logging system",
        "Created custom exception hierarchy",
        "Created utility decorators"
    ]

    print("\n📦 Archiving critical files...")
    archived_files = []

    for file_path in critical_files:
        if Path(file_path).exists():
            archived = archiver.archive_file(
                file_path, "pre_ui_implementation")
            if archived:
                archived_files.append(archived)

    print(f"\n✅ Archived {len(archived_files)} files")

    # Create version log
    print("\n📝 Creating version log...")
    log_file = archiver.create_version_log(changes)

    print("\n" + "=" * 60)
    print("Archive Complete!")
    print("=" * 60)
    print(f"Archived files: {len(archived_files)}")
    print(f"Version log: {log_file}")
    print(f"Archive location: {archiver.archive_dir}")

    return archived_files, log_file


if __name__ == "__main__":
    archive_current_version()
