
import base64
import logging
import os
from datetime import datetime
from typing import Any, Dict, List

import cv2
import numpy as np

logger = logging.getLogger("SJ_DAS.Core.Reporting")


class TechSheetGenerator:
    """
    Generates Professional Tech Sheets for Manufacturing.
    Output: HTML (Print-to-PDF ready).
    """

    def __init__(self):
        self.template = """
<!DOCTYPE html>
<html>
<head>
    <title>Tech Sheet - ${design_name}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; margin: 40px; color: #333; }
        .header { display: flex; justify-content: space-between; border-bottom: 2px solid #000; padding-bottom: 20px; }
        .logo { font-size: 24px; font-weight: bold; color: #6366F1; }
        .meta { text-align: right; font-size: 14px; }

        .section { margin-top: 30px; }
        h2 { border-bottom: 1px solid #ccc; padding-bottom: 5px; font-size: 18px; color: #444; }

        .preview-container { display: flex; gap: 20px; }
        .main-preview { flex: 2; border: 1px solid #ddd; }
        .main-preview img { width: 100%; height: auto; display: block; }

        .specs { flex: 1; background: #f9f9f9; padding: 15px; border-radius: 4px; }
        .spec-item { margin-bottom: 10px; font-size: 14px; }
        .spec-label { font-weight: bold; display: block; color: #666; }

        .palette { display: flex; flex-wrap: wrap; gap: 10px; margin-top: 10px; }
        .swatch { width: 40px; height: 40px; border: 1px solid #ddd; border-radius: 4px; }

        .footer { margin-top: 50px; font-size: 12px; color: #888; text-align: center; border-top: 1px solid #eee; padding-top: 20px; }

        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { text-align: left; padding: 8px; border-bottom: 1px solid #ddd; font-size: 14px; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <div class="header">
        <div class="logo">SJ-DAS <span style="font-weight:normal; color:#555;">Professional</span></div>
        <div class="meta">
            Design ID: <strong>${design_id}</strong><br>
            Date: <strong>${date}</strong><br>
            Designer: <strong>${designer}</strong>
        </div>
    </div>

    <div class="section">
        <div class="preview-container">
            <div class="main-preview">
                <img src="data:image/png;base64,${design_image_b64}" alt="Design Preview">
            </div>
            <div class="specs">
                <h2>Loom Configuration</h2>
                <div class="spec-item">
                    <span class="spec-label">Loom Type</span>
                    Jacquard Electronic
                </div>
                <div class="spec-item">
                    <span class="spec-label">Hooks (Warp)</span>
                    ${hooks}
                </div>
                <div class="spec-item">
                    <span class="spec-label">Picks (Weft)</span>
                    ${picks}
                </div>
                <div class="spec-item">
                    <span class="spec-label">Resolution</span>
                    ${resolution}
                </div>

                 <h2>Yarn Pallete</h2>
                 <div class="palette">
                     ${palette_html}
                 </div>
            </div>
        </div>
    </div>

    <div class="section">
        <h2>Weave Mapping</h2>
        <table>
            <thead>
                <tr>
                    <th>Color Index</th>
                    <th>Color (RGB)</th>
                    <th>Weave Structure</th>
                    <th>Weft Yarn</th>
                </tr>
            </thead>
            <tbody>
                ${mapping_rows}
            </tbody>
        </table>
    </div>

    <div class="footer">
        Generated by SJ-DAS Professional | Licensed to ${designer} | Confidential Manufacturing Document
    </div>
</body>
</html>
"""

    def generate_report(self,
                        design_img: np.ndarray,
                        metadata: Dict[str, Any],
                        output_path: str) -> bool:
        """
        Generates the HTML report.
        Args:
            design_img: BGR numpy array
            metadata: Dict with keys: 'name', 'designer', 'hooks', 'picks', 'palette'
            output_path: Path to save .html file
        """
        try:
            logger.info(f"Generating Tech Sheet for {output_path}")

            # 1. Prepare Image (Base64)
            _, buffer = cv2.imencode('.png', design_img)
            img_b64 = base64.b64encode(buffer).decode('utf-8')

            # 2. Process Palette & Mappings
            # metadata['palette'] expected as list of (r,g,b) tuples
            palette = metadata.get('palette', [])
            palette_html = ""
            mapping_rows = ""

            for i, color in enumerate(palette):
                r, g, b = color
                hex_col = f"#{r:02x}{g:02x}{b:02x}"
                # Swatches
                palette_html += f'<div class="swatch" style="background-color: {hex_col};" title="Index {i}: {hex_col}"></div>'

                # Table Rows
                mapping_rows += f"""
                <tr>
                    <td>{i}</td>
                    <td><span style="display:inline-block;width:12px;height:12px;background:{hex_col};margin-right:5px;border:1px solid #ccc;"></span> {r},{g},{b}</td>
                    <td>{metadata.get('weaves', {}).get(i, 'Plain')}</td>
                    <td>{metadata.get('yarns', {}).get(i, 'Standard Viscose')}</td>
                </tr>
                """

            # 3. Fill Template
            from string import Template
            t = Template(self.template)

            html_content = t.safe_substitute({
                'design_name': metadata.get('name', 'Untitled Design'),
                'design_id': f"DSN-{datetime.now().strftime('%Y%m%d-%H%M')}",
                'date': datetime.now().strftime("%Y-%m-%d %H:%M"),
                'designer': metadata.get('designer', 'Unknown'),
                'design_image_b64': img_b64,
                'hooks': metadata.get('hooks', 2400),
                'picks': metadata.get('picks', 3000),
                'resolution': f"{metadata.get('width', 0)}x{metadata.get('height', 0)} px",
                'palette_html': palette_html,
                'mapping_rows': mapping_rows
            })

            # 4. Save
            os.makedirs(os.path.dirname(output_path), exist_ok=True)
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(html_content)

            logger.info("Tech Sheet generated successfully.")
            return True

        except Exception as e:
            logger.error(f"Failed to generate Tech Sheet: {e}", exc_info=True)
            return False
